version: "3"
services:
  manager:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/code-complexity-analysis/manager/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4008:80"