version: "3"
services:
  worker1:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/code-complexity-analysis/worker/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4010:80"
  worker2:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/code-complexity-analysis/worker/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
  worker3:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/code-complexity-analysis/worker/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "6000:80"
  worker4:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/code-complexity-analysis/worker/'
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7000:80"